trigger:
  branches:
    include: [main, test*]
  tags:
    include: ['*']


jobs:
- template: job--python-tox.yml
  parameters:
    coverage: false
    toxenvs: [py37, py38, py39, py310, py311, py312, pypy3, docs]
